### ISSUE TITLE
Update dependencies to support new Zeebe ErrorType

### ISSUE THREAD

**Issue by remcowesterhoud** [Zelldon/zdb#166]
Zeebe has introduced the `CALLED_DECISION_ERROR` error type. These errors will now cause zdb to break. Updating the dependencies should solve the issue.

```
remco@Remcos-MacBook-Pro snapshots % zdb status -p=/Users/remco/Documents/Work/data/raft-partition/partitions/2/runtime
java.lang.RuntimeException: Unexpected error occurred during zeebe db transaction operation.
	at io.zell.zdb.db.readonly.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:33)
	at io.zell.zdb.db.readonly.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:52)
	at io.zell.zdb.db.readonly.transaction.TransactionalColumnFamily.lambda$whileEqualPrefix$8(TransactionalColumnFamily.java:250)
	at io.zell.zdb.db.readonly.transaction.ColumnFamilyContext.withPrefixKey(ColumnFamilyContext.java:111)
	at io.zell.zdb.db.readonly.transaction.TransactionalColumnFamily.whileEqualPrefix(TransactionalColumnFamily.java:247)
	at io.zell.zdb.db.readonly.transaction.TransactionalColumnFamily.whileEqualPrefix(TransactionalColumnFamily.java:209)
	at io.zell.zdb.db.readonly.transaction.TransactionalColumnFamily.forEach(TransactionalColumnFamily.java:156)
	at io.zell.zdb.db.readonly.transaction.TransactionalColumnFamily.forEach(TransactionalColumnFamily.java:95)
	at io.zell.zdb.state.incident.IncidentState.listIncidents(IncidentState.kt:43)
	at io.zell.zdb.state.general.GeneralState.incidentDetails(GeneralState.kt:84)
	at io.zell.zdb.state.general.GeneralState.generalDetails(GeneralState.kt:29)
	at io.zell.zdb.StatusCommand.call(StatusCommand.java:31)
	at io.zell.zdb.StatusCommand.call(StatusCommand.java:16)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.zell.zdb.ZeebeDebugger.main(ZeebeDebugger.java:51)
Caused by: java.lang.RuntimeException: Could not deserialize object [Incident]. Deserialization stuck at offset 49 of length 334
	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:38)
	at io.zell.zdb.db.readonly.transaction.TransactionalColumnFamily.visit(TransactionalColumnFamily.java:289)
	at io.zell.zdb.db.readonly.transaction.TransactionalColumnFamily.lambda$whileEqualPrefix$7(TransactionalColumnFamily.java:270)
	at io.zell.zdb.db.readonly.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$0(TransactionalColumnFamily.java:53)
	at io.zell.zdb.db.readonly.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:27)
	... 21 more
Caused by: java.lang.RuntimeException: Could not read property 'incidentRecord'
	at io.camunda.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:112)
	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:32)
	... 25 more
Caused by: java.lang.RuntimeException: Could not read property 'errorType'
	at io.camunda.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:112)
	at io.camunda.zeebe.msgpack.property.BaseProperty.read(BaseProperty.java:75)
	at io.camunda.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:110)
	... 26 more
Caused by: java.lang.RuntimeException: Illegal enum value: CALLED_DECISION_ERROR.
	at io.camunda.zeebe.msgpack.value.EnumValue.read(EnumValue.java:74)
	at io.camunda.zeebe.msgpack.property.BaseProperty.read(BaseProperty.java:75)
	at io.camunda.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:110)
	... 28 more
```

**Comment by Zelldon** [comment]
Done via 1.4.0
