### ISSUE TITLE
Unexpected special floating-point value NaN

### ISSUE THREAD

**Issue by korthout** [Zelldon/zdb#20]
Running `zdb log status --path="./raft-partition/partitions/1/"` I encountered the following exception:

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
kotlinx.serialization.json.internal.JsonEncodingException: Unexpected special floating-point value NaN. By default, non-finite floating point values are prohibited because they do not conform JSON specification. It is possible to deserialize them using 'JsonBuilder.allowSpecialFloatingPointValues = true'
Current output: {"avgEntrySize":NaN
	at kotlinx.serialization.json.internal.JsonExceptionsKt.InvalidFloatingPointEncoded(JsonExceptions.kt:34)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeDouble(StreamingJsonEncoder.kt:195)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeDoubleElement(AbstractEncoder.kt:63)
	at io.zell.zdb.log.LogStatusDetails$$serializer.serialize(LogStatusDetails.kt:7)
	at io.zell.zdb.log.LogStatusDetails$$serializer.serialize(LogStatusDetails.kt:7)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:211)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:80)
	at io.zell.zdb.log.LogStatusDetails.toString(LogStatusDetails.kt:24)
	at java.base/java.lang.String.valueOf(String.java:3388)
	at java.base/java.io.PrintStream.println(PrintStream.java:1047)
	at io.zell.zdb.LogCommand.status(LogCommand.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1952)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at io.zell.zdb.ZeebeDebugger.main(ZeebeDebugger.java:51)
```

I don't know much about the given log (I have a feeling that this might be a fully compacted log). I'll keep the log around in case we want to tackle this problem.

**Comment by Zelldon** [comment]
@korthout thanks for reporting. Could you attach the log?

**Comment by korthout** [comment]
@Zelldon Sorry no, it concerns production data that I was analyzing
